# Generated by Django 5.2.14 on 2026-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_orders_orde_created_0e92de_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_fabric',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_is_stitched',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
