# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.FileField(blank=True, upload_to="categories/"),
        ),
    ]
