# Generated by Django 5.2.14 on 2026-06-11 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productimage_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='product-color-images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product-color-images/thumbnails/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.productcolorvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_stitched',
            field=models.BooleanField(default=False, help_text='True = stitched, False = unstitched. Only relevant when fabric variants differ.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this overrides the product-level sale price for this variant.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color', 'fabric', 'is_stitched')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['color_variant'], name='catalog_pro_color_v_4943cf_idx'),
        ),
        migrations.AddField(
            model_name='productcolorvariantimage',
            name='color_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productcolorvariant'),
        ),
        migrations.AddIndex(
            model_name='productcolorvariantimage',
            index=models.Index(fields=['color_variant', 'sort_order'], name='catalog_pro_color_v_a13769_idx'),
        ),
        migrations.AddIndex(
            model_name='productcolorvariantimage',
            index=models.Index(fields=['created_at'], name='catalog_pro_created_477536_idx'),
        ),
    ]
