# Generated by Django 5.2.14 on 2026-06-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_variant_gallery_and_stock_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='product-variant-images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product-variant-images/thumbnails/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['variant', 'sort_order'], name='catalog_pro_variant_04512c_idx'), models.Index(fields=['created_at'], name='catalog_pro_created_ef0e41_idx')],
            },
        ),
    ]
