# Generated by Codex on 2026-06-06

from django.db import migrations, models


def dedupe_reviews(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    seen = set()
    for review in Review.objects.order_by("user_id", "product_id", "-updated_at", "-created_at", "-id"):
        key = (review.user_id, review.product_id)
        if key in seen:
            review.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="customer_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="review",
            name="customer_profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/profiles/"),
        ),
        migrations.AddField(
            model_name="review",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="review_image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
        migrations.AddField(
            model_name="review",
            name="verified_purchase",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("hidden", "Hidden spam")], default="pending", max_length=16),
        ),
        migrations.RunPython(dedupe_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(fields=("user", "product"), name="unique_review_per_user_product"),
        ),
    ]
