# Generated by Codex on 2026-06-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_guest_fields(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    for review in Review.objects.all():
        changed = []
        if not review.guest_name:
            review.guest_name = review.customer_name or ""
            changed.append("guest_name")
        if not review.review_text:
            review.review_text = review.comment or ""
            changed.append("review_text")
        if not review.image and review.review_image:
            review.image = review.review_image
            changed.append("image")
        if changed:
            review.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_real_customer_reviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_review_per_user_product",
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviews", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="review",
            name="guest_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="review",
            name="review_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
        migrations.AddField(
            model_name="review",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_guest_fields, migrations.RunPython.noop),
    ]
