# Generated by Codex on 2026-06-06

from django.db import migrations, models


def sync_is_approved(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    Review.objects.filter(status="approved").update(is_approved=True)
    Review.objects.exclude(status="approved").update(is_approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_guest_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(sync_is_approved, migrations.RunPython.noop),
    ]
