# Generated by Django 5.2.14 on 2026-05-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('cod', 'Cash on Delivery'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
