# Generated by Django 5.2.14 on 2026-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_id', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='started', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
